package XCOMApp::Model::Schema;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'XCOMApp::Schema',

    connect_info => {
        dsn => 'dbi:SQLite:dbname=xcom_app.sqlite'
    }
);

=head1 NAME

XCOMApp::Model::Schema - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<XCOMApp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<XCOMApp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

William Lang

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
